### ISSUE TITLE
Conditional Search

### ISSUE THREAD

**Issue by nium9** [dataabc/weibo-search#123]
Not really a issue
but how would you do condition search similar to twitter, like for example
world ("cup" or "football")
so it shows weibos with "world football" and weibos with "world cup"

**Comment by cloudy-sfu** [comment]
Thank you. We faithfully forward your searching words to the input box at "weibo.com" website. Since weibo doesn't provide the conditional search function, we cannot do this either.

The searching box of "weibo.com" is as the following picture:
![image](https://user-images.githubusercontent.com/41314224/142406068-c1638b48-cb3b-460e-956c-33e2ded1e9f8.png)

**Comment by dataabc** [comment]
If you want to get the weibos including keyword1 and keyword2，you should set the argument KEYWORD_LIST in settings.py
···
KEYWORD_LIST = "keyword1 keyword2"
# for example 
# KEYWORD_LIST = "world cup football"
···
If you need the weibos including keyword1 or keyword2, you should set the same argument in settings.py like this
```
KEYWORD_LIST = ["keyword1", "keyword2"]
# for example
# KEYWORD_LIST = ["world cup", "world football"]
```
